@startuml
|User|
start
:Выбрать тип задачи;
|Repository|
:Выбрать допустимые модели;
:Выбрать алгоритмы и метрики качества;
|User|
:Загрузить подготовленные данные;
:Запустить алгоритм композирования;
|Composer|
:Сформировать начальную популяцию цепочек моделей;
if (Метрика качества < Допустимый порог) then (Нет)
:Вычислить цепочки моделей;
|Executor|
if (Все узлы вычислены?) then (Нет)
:Выбрать следующий узел;
:Обучить модель у текущего узла;
:Вычислить модель на тестовых данных;
:Закэшировать модель и результаты;
else (Да)
Endif
else (Да)
Endif
|Composer|
:Получить итоговую цепочку моделей;
|Packer|
:Сформировать шаблон цепочки;
:Упаковать обученную цепочку моделей в Docker;
|User|
:Отобразить итоговую цепочку моделей;
:Сохранить шаблон цепочки и Docker-контейнер;
stop
@enduml